### ISSUE TITLE
Error when i try to build it on osx 10.13.3

### ISSUE THREAD

**Issue by alonsoir** [PWhiddy/Nbody-Gravity#3]
`MacBook-Pro-Retina-de-Alonso:Nbody-Gravity aironman$ ./build.bash 
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'`

**Comment by PWhiddy** [comment]
It appears that some versions of clang on MacOS don't support openmp.

You have two options:

1. Try to install a different c++ compiler, there is a discussion regarding this same issue here 
(https://github.com/ppwwyyxx/OpenPano/issues/16)

2. Just remove the -fopenmp option from build.sh
This will work immediately, but will reduce performance somewhat
